// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RadioButtonsController from "./radio_buttons_controller"
application.register("radio-buttons", RadioButtonsController)

import ResetController from "./reset_controller"
application.register("reset", ResetController)
